#!/bin/bash

amixer -c 2 cset name='Speaker Switch' off
amixer -c 2 cset name='Stereo DAC MIXL DAC1 R Switch' off
amixer -c 2 cset name='Stereo DAC MIXR DAC1 L Switch' off
amixer -c 2 cset name='Stereo DAC MIXL DAC1 L Switch' on
amixer -c 2 cset name='Stereo DAC MIXR DAC1 R Switch' on
amixer -c 2 cset name='OUT1 Playback Switch' on
amixer -c 2 cset name='OUT2 Playback Switch' on
amixer -c 2 cset name='Headphone Switch' on
