#!/bin/bash

amixer -c 2 cset name='Headphone Switch' off
amixer -c 2 cset name='Stereo DAC MIXL DAC1 L Switch' off
amixer -c 2 cset name='Stereo DAC MIXR DAC1 R Switch' off
amixer -c 2 cset name='Stereo DAC MIXL DAC1 R Switch' on
amixer -c 2 cset name='Stereo DAC MIXR DAC1 L Switch' on
amixer -c 2 cset name='Speaker Switch' on
